
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: seller
          uri: lb://eureka-client-admin #lb表示开启负载均衡，使用应用名称进行转发
          predicates: #将 gateway/v1/seller/* 转发至 uri/v1/seller/*
            - Path=/v1/seller/*
        - id: admin
          uri: http://localhost:9001/
          predicates: #将 gateway/v1/admin/* 转发至 uri/v1/admin/*
            - Path=/v1/admin/*
    nacos:
      discovery:
        server-addr: http://localhost:8848
  application:
    name: cloud-gateway

server:
  port: 8000
